/*INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('a',2, 'b','c','d')
*/
   
INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 11, 'vrsta_podloge', 'Platno',  'Platno'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 11, 'vrsta_podloge', 'Papir',  'Papir'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 11, 'vrsta_podloge', 'Flex',  'Flex'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 9, 'proizvodjac','Dunlop',  'Dunlop'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 9, 'proizvodjac','Kleiberit',  'Kleiberit'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 4, 'namjena', 'Za tapaciranje' , 'Za tapaciranje'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 4, 'namjena', 'Za pakovanje' , 'Za pakovanje'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 5, 'namjena', 'Za tapaciranje' , 'Za tapaciranje'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 11, 'namjena', 'Brušenje drveta' , 'Brušenje drveta'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 11, 'namjena', 'Brušenje temeljnog laka' , 'Brušenje temeljnog laka'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 4, 'forma_oblik', 'Plašt','Plašt'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 4, 'forma_oblik', 'Kutija', 'Kutija'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 5, 'sp_tezina', '1.1', '1.1'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 5, 'sp_tezina', '1.2', '1.2'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 6, 'gustina', '30', '30'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 6, 'gustina', '40', '40'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 6, 'gustina', '50', '50'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 6, 'tvrdoca', '20T' ,'20T'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 6, 'tvrdoca', '25T' ,'25T'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 6, 'tvrdoca', '30T' ,'30T'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 6, 'tvrdoca', '18PT', '18PT'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 1, 'klasa', 'AB', 'AB'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 1, 'klasa', 'BC', 'BC'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 1, 'klasa', 'CD', 'CD'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 2, 'klasa', 'Sirova', 'Sirova'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 2, 'klasa', 'Bijela', 'Bijela'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 2, 'klasa', 'Oplemenjena', 'Oplemenjena'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 2, 'klasa', 'AA', 'AA'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 2, 'klasa', 'AC', 'AC'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 2, 'klasa', 'CC-tapaciranje', 'CC-tapaciranje'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 4, 'klasa', 'B-2Š', 'B-2Š'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 4, 'klasa', 'B-TŠ', 'B-TŠ'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 4, 'klasa', 'B-2T', 'B-2T'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 4, 'klasa', 'CB-T2Š', 'CB-T2Š'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 4, 'klasa', '1100gr', '1100gr'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 5, 'klasa', 'A', 'A'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 6, 'klasa', 'A', 'A'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 6, 'klasa', 'B', 'B'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 3, 'br_linija', '3', '3'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 3, 'br_linija', '4', '4'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 4, 'br_slojeva', '3', '3'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 4, 'br_slojeva', '5', '5'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 3, 'sirina', '50','50'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 3, 'sirina', '60','60'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 3, 'sirina', '70','70'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 1, 'duz_razred', '600', 'do 600'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 1, 'duz_razred', '900', '600-900'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 1, 'duz_razred', 'preko_900', 'preko 900'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 11,'granulacija', '120', '120'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 11,'granulacija', '150', '150'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 11,'granulacija', '180', '180'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 11,'granulacija', '280', '280'
);INSERT INTO config_sifre (tabela, mattip_id, polje, sifra, opis) VALUES('materijali', 11,'granulacija', '600', '600');